### PR TITLE
Added DRI access

### PR DESCRIPTION
**Pull request by hfiguiere**
This should solve
```
libEGL warning: wayland-egl: could not open /dev/dri/renderD128 (No such file or directory)
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
```

### CODE REVIEW

**Comment by hfiguiere** [comment]
Build fails because appstream file reference screenshot from `master` instead of a commit or tag. And the branch was renamed.

**Comment by Hofer-Julian** [comment]
> Build fails because appstream file reference screenshot from `master` instead of a commit or tag. And the branch was renamed.

Yes, we changed the branch yesterday and we still ought to make a new release

**Comment by hfiguiere** [comment]
referencing a branch there is always a bad idea.

**Comment by hfiguiere** [comment]
The build will fail because appstreamcli think the purism form factor is in error.

**Comment by hfiguiere** [comment]
For removal of the Purism keys: https://github.com/ximion/appstream/issues/476

**Comment by hfiguiere** [comment]
ok to merge this in the mean time?

**Pull request merged**
